In [1]:
import numpy as np 

import pandas as pd

from IPython.display import display

In [2]:
customers = pd.read_csv('customers.csv')
items = pd.read_csv('Items.csv')
order_item = pd.read_csv('order_item.csv')
orders = pd.read_csv('orders.csv')

In [3]:
print(f'-> Question 1\n')
print(f'-> Part 1 / Task 1 - Explore the tables :\n')

# 1.1 — Exploring the information in the tables
# Explore the information in the four tables. 
# For each table, print the column names, data types, number of non-null values, 
# and other relevant information.

print(f' --------------customers - table-------------- \n')
display(customers.info())
print(f'\n --------------items - table--------------\n')
display(items.info())
print(f'\n --------------order_item - table-------------- \n')
display(order_item.info())
print(f'\n --------------orders - table-------------- \n')
display(orders.info())

-> Question 1

-> Part 1 / Task 1 - Explore the tables :

 --------------customers - table--------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            500 non-null    int64
 1   first_name    500 non-null    object
 2   last_name     500 non-null    object
 3   gender        442 non-null    object
 4   age           475 non-null    float64
 5   nationallity  500 non-null    object
 6   joining_date  439 non-null    object
 7   phone_number  492 non-null    object
 8   email         500 non-null    object
dtypes: float64(1), int64(1), object(7)
memory usage: 35.3+ KB

None

 --------------items - table--------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 50 non-null     int64
 1   item_name          50 non-null     object
 2   item_category      42 non-null     object
 3   item_price         50 non-null     float64
 4   stock_quantity     45 non-null     float64
 5   item_brand         40 non-null     object
 6   item_availability  50 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 2.5+ KB

None

 --------------order_item - table--------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1000 non-null   int64
 1   id          1000 non-null   int64
 2   order_id    1000 non-null   int64
 3   item_id     960 non-null    float64
 4   quantity    1000 non-null   int64
dtypes: float64(1), int64(4)
memory usage: 39.2 KB

None

 --------------orders - table--------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          600 non-null    int64
 1   customer_id       555 non-null    float64
 2   delivery_address  600 non-null    object
 3   delivery_days     525 non-null    float64
 4   order_date        600 non-null    object
 5   payment_method    600 non-null    object
 6   order_source      600 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 32.9+ KB

None

In [4]:
print(f'-> Part 1 / Task 2 - Summary statistics :\n')

# 1.2 — Summary statistics
# For each table, print the column names, 
# average values, maximum values, minimum values, 
# and other statistical information.

print(f' --------------customers - table-------------- \n')
display(customers.describe().T)
print(f'\n --------------Items - table--------------\n')
display(items.describe().T)
print(f'\n --------------order_item - table-------------- \n')
display(order_item.describe().T)
print(f'\n --------------orders - table-------------- \n')
display(orders.describe().T)

-> Part 1 / Task 2 - Summary statistics :

 --------------customers - table--------------

     count        mean         std  min     25%    50%     75%    max
id   500.0  250.500000  144.481833  1.0  125.75  250.5  375.25  500.0
age  475.0   44.006316   14.813395  2.0   34.00   44.0   55.00   84.0

 --------------Items - table--------------

,count,mean,std,min,25%,50%,75%,max
id,50.0,25.500000,14.577380,1.00,13.25,25.50,37.75,50.00
item_price,50.0,2222.082600,1394.005145,241.54,1004.36,1956.22,3436.83,4471.27
stock_quantity,45.0,743.155556,332.855071,14.00,550.00,704.00,971.00,1367.00

 --------------order_item - table--------------

             count        mean         std  min     25%    50%     75%     max
Unnamed: 0  1000.0  499.500000  288.819436  0.0  249.75  499.5  749.25   999.0
id          1000.0  500.500000  288.819436  1.0  250.75  500.5  750.25  1000.0
order_id    1000.0  305.006000  171.251432  1.0  157.00  315.0  450.00   599.0
item_id      960.0   25.746875   14.676686  1.0   13.00   26.0   38.00    50.0
quantity    1000.0    3.016000    2.288882  1.0    1.00    2.0    4.00     9.0

 --------------orders - table--------------

,count,mean,std,min,25%,50%,75%,max
order_id,600.0,300.500000,173.349358,1.0,150.75,300.5,450.25,600.0
customer_id,555.0,258.650450,146.002993,1.0,136.00,256.0,385.00,500.0
delivery_days,525.0,3.899048,1.075091,1.0,3.00,4.0,5.00,6.0

In [5]:
print(f'-> Part 1 / Task 3 - First five rows :\n')

# 1.3 — Print the first five rows
# Print the first five values/rows of each table.

print(f' --------------customers - table-------------- \n')
display(customers.head(5))
print(f'\n --------------Items - table--------------\n')
display(items.head(5))
print(f'\n --------------order_item - table-------------- \n')
display(order_item.head(5))
print(f'\n --------------orders - table-------------- \n')
display(orders.head(5))

-> Part 1 / Task 3 - First five rows :

 --------------customers - table--------------

,id,first_name,last_name,gender,age,nationallity,joining_date,phone_number,email
0,1,Eadie,Maffeo,Female,41.0,France,11/01/2022,534-341-9052,emaffeo0@smh.com.au
1,2,Hammad,Brewerton,Male,56.0,Isreal,30/09/2022,999-994-0510,hbrewerton1@discovery.com
2,3,Terrell,Bris,NaN,43.0,India,NaN,980-455-5208,tbris2@yale.edu
3,4,Frannie,Morewood,Male,84.0,France,26/05/2021,979-187-1493,fmorewood3@vistaprint.com
4,5,Sophi,Fleet,Female,33.0,Sweden,19/07/2021,991-853-9984,sfleet4@unicef.org

 --------------Items - table--------------

,id,item_name,item_category,item_price,stock_quantity,item_brand,item_availability
0,1,Television,Televisions and Displays,356.81,1009.0,NaN,True
1,2,Laptop,Computers and Accessories,1851.32,493.0,NaN,True
2,3,Desktop,Computers and Accessories,1121.84,334.0,HP,True
3,4,Smartphone,Mobile Devices and Accessories,965.20,201.0,NaN,True
4,5,Tablet,NaN,2739.61,190.0,Toshiba,True

 --------------order_item - table--------------

   Unnamed: 0  id  order_id  item_id  quantity
0           0   1       337     10.0         2
1           1   2       430     27.0         6
2           2   3       430     36.0         2
3           3   4       508     46.0         1
4           4   5       229     27.0         2

 --------------orders - table--------------

,order_id,customer_id,delivery_address,delivery_days,order_date,payment_method,order_source
0,1,477.0,576 Cordelia Place,2.0,2023-12-05,GIFT_CARD,WEBSITE
1,2,93.0,4664 6th Drive,4.0,2023-08-17,CASH,STORE
2,3,474.0,8766 4th Point,4.0,2023-02-25,CHECK,STORE
3,4,333.0,31 Bonner Way,3.0,2023-02-04,CASH,STORE
4,5,436.0,20352 Shelley Way,5.0,2023-06-01,CASH,STORE

In [6]:
print(f'-> Part 1 / Task 4 + 4.1 - Count non-null values :\n')

# 1.4 — Finding duplicate products
# There are products in the Items table that appear more than once (products with the same name). 
# Keep the product with the same name that has the highest number of non-null values,
# and delete the others

# 1.4.1 — Count the non-null values
# Add a new column that counts how many non-null values each row contains.

duplicates_items = items[items.duplicated(subset=['item_name'], keep=False)].copy()

duplicates_items['not_null'] = duplicates_items.notnull().sum(axis=1)

display(duplicates_items)

-> Part 1 / Task 4 + 4.1 - Count non-null values :

,id,item_name,item_category,item_price,stock_quantity,item_brand,item_availability,not_null
0,1,Television,Televisions and Displays,356.81,1009.0,NaN,True,6
1,2,Laptop,Computers and Accessories,1851.32,493.0,NaN,True,6
2,3,Desktop,Computers and Accessories,1121.84,334.0,HP,True,7
3,4,Smartphone,Mobile Devices and Accessories,965.20,201.0,NaN,True,6
4,5,Tablet,NaN,2739.61,190.0,Toshiba,True,6
5,6,Printer,Printers and Office Equipment,4175.99,971.0,Sony,True,7
6,7,Camera,Photography Equipment,2366.72,458.0,NaN,True,6
7,8,Headphone,NaN,3117.19,599.0,NaN,True,5
8,9,Speaker,Audio Equipment,4471.27,1360.0,Toshiba,True,7
41,42,Television,Televisions and Displays,479.19,670.0,Samsung,True,7
42,43,Laptop,Computers and Accessories,4153.61,1018.0,Dell,True,7
43,44,Desktop,Computers and Accessories,723.59,1119.0,NaN,True,6
44,45,Smartphone,Mobile Devices and Accessories,3513.56,1162.0,Panasonic,True,7
45,46,Tablet,Mobile Devices and Accessories,1606.65,267.0,HP,True,7
46,47,Printer,Printers and Office Equipment,3704.16,239.0,NaN,True,6
47,48,Camera,Photography Equipment,2039.08,471.0,Panasonic,True,7
48,49,Headphone,Audio Equipment,1317.56,NaN,Sony,False,6
49,50,Speaker,Audio Equipment,4453.90,937.0,NaN,True,6

In [7]:
print(f'-> Part 1 / Task 4.2 - Sort :\n')

#1.4.2 — Sort the products
# Sort the table by product name and by the new non-null-count column, 
# from largest to smallest.
    
duplicates_items.sort_values(by=['item_name', 'not_null'], ascending=[False, False], inplace=True)
display(duplicates_items)

-> Part 1 / Task 4.2 - Sort :

,id,item_name,item_category,item_price,stock_quantity,item_brand,item_availability,not_null
41,42,Television,Televisions and Displays,479.19,670.0,Samsung,True,7
0,1,Television,Televisions and Displays,356.81,1009.0,NaN,True,6
45,46,Tablet,Mobile Devices and Accessories,1606.65,267.0,HP,True,7
4,5,Tablet,NaN,2739.61,190.0,Toshiba,True,6
8,9,Speaker,Audio Equipment,4471.27,1360.0,Toshiba,True,7
49,50,Speaker,Audio Equipment,4453.90,937.0,NaN,True,6
44,45,Smartphone,Mobile Devices and Accessories,3513.56,1162.0,Panasonic,True,7
3,4,Smartphone,Mobile Devices and Accessories,965.20,201.0,NaN,True,6
5,6,Printer,Printers and Office Equipment,4175.99,971.0,Sony,True,7
46,47,Printer,Printers and Office Equipment,3704.16,239.0,NaN,True,6
42,43,Laptop,Computers and Accessories,4153.61,1018.0,Dell,True,7
1,2,Laptop,Computers and Accessories,1851.32,493.0,NaN,True,6
48,49,Headphone,Audio Equipment,1317.56,NaN,Sony,False,6
7,8,Headphone,NaN,3117.19,599.0,NaN,True,5
2,3,Desktop,Computers and Accessories,1121.84,334.0,HP,True,7
43,44,Desktop,Computers and Accessories,723.59,1119.0,NaN,True,6
47,48,Camera,Photography Equipment,2039.08,471.0,Panasonic,True,7
6,7,Camera,Photography Equipment,2366.72,458.0,NaN,True,6

In [8]:
print(f'-> Part 1 / Task  4.3 - Remove duplicate products :\n')

# 1.4.3 — Remove duplicate product names
# Remove duplicate products based on the product name, keeping only the first occurrence.

duplicated_ids = duplicates_items.drop_duplicates(subset=['item_name'], keep='last')
print("-> Duplicate item IDs marked for removal:")
display(duplicated_ids[['id', 'item_name']].T)

unduplicated_ids = duplicates_items.drop_duplicates(subset=['item_name'], keep='first')
print("-> Unique item IDs that will be retained:")
display(unduplicated_ids[['id', 'item_name']].T)

-> Part 1 / Task  4.3 - Remove duplicate products :

-> Duplicate item IDs marked for removal:

,0,4,49,3,46,1,7,43,6
id,1,5,50,4,47,2,8,44,7
item_name,Television,Tablet,Speaker,Smartphone,Printer,Laptop,Headphone,Desktop,Camera

-> Unique item IDs that will be retained:

,41,45,8,44,5,42,48,2,47
id,42,46,9,45,6,43,49,3,48
item_name,Television,Tablet,Speaker,Smartphone,Printer,Laptop,Headphone,Desktop,Camera

In [10]:
print(f'-> Part 1 / Task  4.4 - Update duplicate product IDs :\n')

# 1.4.4 — Update the order_item table
# Replace the IDs of duplicated products in the order_item table 
# with the ID of the product that has the highest number of non-null values.

id_to_name = items[['id', 'item_name']].set_index('id')['item_name'].sort_values()


keeps_id = new_items.set_index('item_name')['id']
drops_id = duplicated_ids.set_index('item_name')['id']

order_item['item_id'] = order_item['item_id'].map(id_to_name).map(keeps_id)

print("-> Target IDs (To Keep):")
display(keeps_id.to_frame())

print("-> Redundant IDs (To Replace):")
display(drops_id.to_frame().T)

-> Part 1 / Task  4.4 - Update duplicate product IDs :

-> Target IDs (To Keep):

                       id
item_name
Desktop                 3
Printer                 6
Speaker                 9
DVD Player             10
Blu-Ray Player         11
Video Game Console     12
Video Game             13
Smart Watch            14
Fitness Tracker        15
Drone                  16
Projector              17
Computer Monitor       18
Keyboard               19
Mouse                  20
External Hard Drive    21
USB Flash Drive        22
Micro SD Card          23
Digital Picture Frame  24
Camcorder              25
Action Camera          26
Dash Camera            27
CCTV Camera            28
Webcam                 29
Gaming Chair           30
Wireless Charger       31
Portable Charger       32
Surge Protector        33
HDMI Cable             34
Wi-Fi Router           35
Modem                  36
Antivirus Software     37
Office Software        38
Power Strip            39
Tripod                 40
VR Headset             41
Television             42
Laptop                 43
Smartphone             45
Tablet                 46
Camera                 48
Headphone              49

-> Redundant IDs (To Replace):

item_name,Television,Tablet,Speaker,Smartphone,Printer,Laptop,Headphone,Desktop,Camera
id,1,5,50,4,47,2,8,44,7

In [9]:
print(f'-> Part 1 / Task 4.4 - update items table with the new ids and indexes:\n')

    
new_items = items[~items['id'].isin(duplicated_ids['id'])].reset_index(drop=True)
display(new_items)

-> Part 1 / Task 4.4 - update items table with the new ids and indexes:

,id,item_name,item_category,item_price,stock_quantity,item_brand,item_availability
0,3,Desktop,Computers and Accessories,1121.84,334.0,HP,True
1,6,Printer,Printers and Office Equipment,4175.99,971.0,Sony,True
2,9,Speaker,Audio Equipment,4471.27,1360.0,Toshiba,True
3,10,DVD Player,Video Players and Recorders,453.85,605.0,NaN,True
4,11,Blu-Ray Player,Video Players and Recorders,3382.86,704.0,ASUS,True
5,12,Video Game Console,Gaming Equipment,689.61,753.0,Microsoft,True
6,13,Video Game,NaN,1890.03,681.0,Lenovo,True
7,14,Smart Watch,Mobile Devices and Accessories,2007.43,742.0,Logitech,True
8,15,Fitness Tracker,Mobile Devices and Accessories,2997.29,956.0,Apple,True
9,16,Drone,NaN,3949.97,850.0,Logitech,True
10,17,Projector,Televisions and Displays,312.88,685.0,Canon,True
11,18,Computer Monitor,Computers and Accessories,4076.35,1205.0,Bose,True
12,19,Keyboard,Computers and Accessories,604.18,NaN,Panasonic,False
13,20,Mouse,Computers and Accessories,1333.04,881.0,Logitech,True
14,21,External Hard Drive,Computers and Accessories,1251.36,1013.0,Microsoft,True
15,22,USB Flash Drive,NaN,1150.87,1251.0,Panasonic,True
16,23,Micro SD Card,Storage Devices,3238.23,663.0,Sony,True
17,24,Digital Picture Frame,Televisions and Displays,4449.99,443.0,Samsung,True
18,25,Camcorder,Photography Equipment,860.01,870.0,Bose,True
19,26,Action Camera,Photography Equipment,2694.25,NaN,Bose,False
20,27,Dash Camera,Photography Equipment,1283.99,550.0,Lenovo,True
21,28,CCTV Camera,NaN,695.71,NaN,Sony,False
22,29,Webcam,Printers and Office Equipment,4227.36,596.0,Dell,True
23,30,Gaming Chair,Gaming Equipment,417.16,704.0,Samsung,True
24,31,Wireless Charger,Mobile Devices and Accessories,241.54,951.0,Lenovo,True
25,32,Portable Charger,Mobile Devices and Accessories,1523.27,192.0,HP,True
26,33,Surge Protector,Printers and Office Equipment,488.39,800.0,ASUS,True
27,34,HDMI Cable,Cables,1710.84,869.0,JBL,True
28,35,Wi-Fi Router,Network Equipment,3812.53,14.0,Microsoft,True
29,36,Modem,NaN,3256.88,673.0,Bose,True
30,37,Antivirus Software,Software,4186.62,NaN,NaN,False
31,38,Office Software,Printers and Office Equipment,3454.82,643.0,JBL,True
32,39,Power Strip,Printers and Office Equipment,3344.90,1211.0,HP,True
33,40,Tripod,Photography Equipment,2055.66,1072.0,Nintendo,True
34,41,VR Headset,NaN,1905.01,1367.0,JBL,True
35,42,Television,Televisions and Displays,479.19,670.0,Samsung,True
36,43,Laptop,Computers and Accessories,4153.61,1018.0,Dell,True
37,45,Smartphone,Mobile Devices and Accessories,3513.56,1162.0,Panasonic,True
38,46,Tablet,Mobile Devices and Accessories,1606.65,267.0,HP,True
39,48,Camera,Photography Equipment,2039.08,471.0,Panasonic,True
40,49,Headphone,Audio Equipment,1317.56,NaN,Sony,False

In [11]:
print(f'-> Part 1 / Task 4.5 - Find customers with 3 or more missing values:\n')

# 1.4.5 — Remove customers with three or more missing fields
# Delete from the customers table all customers who have three or more missing fields.

customers['missing_count'] = customers.isnull().sum(axis=1)

removed_customers = customers[customers['missing_count'] >= 3].drop(columns=['missing_count'])

removed_customer_ids = removed_customers["id"]

display(removed_customers)

-> Part 1 / Task 4.5 - Find customers with 3 or more missing values:

,id,first_name,last_name,gender,age,nationallity,joining_date,phone_number,email
137,138,Ellary,Ledner,NaN,63.0,Peru,NaN,NaN,eledner3t@latimes.com
177,178,Jobyna,Redhills,NaN,NaN,Isreal,10/10/2022,NaN,jredhills4x@gnu.org
196,197,Rosemarie,Morforth,NaN,NaN,Chile,03/08/2021,NaN,rmorforth5g@yahoo.com
204,205,Christy,Shoebrook,Female,NaN,United States,NaN,NaN,cshoebrook5o@ask.com
216,217,Anderea,Rawne,NaN,29.0,Isreal,NaN,NaN,arawne60@ow.ly
354,355,Kayley,Carmo,NaN,33.0,United States,NaN,NaN,kcarmo9u@jugem.jp
406,407,Sharl,Ashpital,NaN,57.0,Isreal,NaN,NaN,sashpitalba@ca.gov
465,466,Natassia,Bransden,Female,NaN,United States,NaN,NaN,nbransdencx@g.co

In [12]:
print(f'-> Part 1 / Task 4.6 - Find their orders and Remove their sales from order_item:\n')

# 1.4.6 — Delete their sales from order_item
# Delete from the order_item table all sales belonging to the customers
# removed in the previous step


removed_orders = orders[orders["customer_id"].isin(removed_customer_ids)]

removed_order_ids = removed_orders["order_id"].tolist()

order_item = order_item[~order_item["order_id"].isin(removed_order_ids)]

# We first find the customers with too many missing values. 
# Then, we find their orders using customer_id. After that, we take the related order_id values. 
# Finally, we delete all sales connected to those orders from the order_item table.

print(f'\n-> Removed orders:')
display(removed_orders)
print(f'\n-> Order IDs of the removed customers:')
display(removed_order_ids)
print(f'\n-> Cleaned order items:')
display(order_item)

-> Part 1 / Task 4.6 - Find their orders and Remove their sales from order_item:


-> Removed orders:

,order_id,customer_id,delivery_address,delivery_days,order_date,payment_method,order_source
101,102,197.0,4016 Stone Corner Plaza,3.0,2023-11-16,CREDIT_CARD,WEBSITE
142,143,407.0,302 Gale Hill,3.0,2023-03-13,CASH,STORE
158,159,197.0,9 Swallow Plaza,5.0,2023-11-07,CHECK,WEBSITE
171,172,205.0,8162 Caliangt Court,3.0,2023-12-12,CREDIT_CARD,WEBSITE
182,183,407.0,30846 Union Circle,3.0,2023-12-22,CREDIT_CARD,WEBSITE
207,208,138.0,4 Pennsylvania Way,4.0,2023-05-25,CASH,STORE
223,224,138.0,7 Ryan Court,NaN,2023-11-26,CHECK,WEBSITE
275,276,138.0,1 Colorado Pass,NaN,2023-05-28,CREDIT_CARD,WEBSITE
287,288,466.0,0 Atwood Junction,5.0,2023-01-02,CHECK,WEBSITE
447,448,138.0,53910 Grim Park,5.0,2023-07-18,CHECK,WEBSITE
456,457,205.0,78770 Victoria Plaza,NaN,2023-04-24,CHECK,WEBSITE
522,523,197.0,793 Swallow Parkway,3.0,2023-01-17,CASH,STORE
556,557,138.0,92961 Lunder Avenue,5.0,2023-06-29,CHECK,WEBSITE

-> Order IDs of the removed customers:

[102, 143, 159, 172, 183, 208, 224, 276, 288, 448, 457, 523, 557]

-> Cleaned order items:

     Unnamed: 0    id  order_id  item_id  quantity
0             0     1       337     10.0         2
1             1     2       430     27.0         6
2             2     3       430     36.0         2
3             3     4       508     46.0         1
4             4     5       229     27.0         2
..          ...   ...       ...      ...       ...
995         995   996       594     24.0         2
996         996   997       330     32.0         8
997         997   998       472     10.0         3
998         998   999       222     29.0         1
999         999  1000       337     16.0         1

[961 rows x 5 columns]